# Starter azure-pipelines.yml

trigger:
- master

pool:
  vmImage: 'macOS-10.15'

variables:
  buildConfiguration: 'Release'

steps:

- task: Xcode@5
  inputs:
    xcWorkspacePath: 'ios/MyApp.xcworkspace'
    scheme: 'MyApp'
    xcToolchain: 'default'
    configuration: '$(buildConfiguration)'
    sdk: 'iphoneos'
    exportMethod: 'ad-hoc'

- task: CopyFiles@2
  inputs:
    contents: '*/.ipa'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
