# Starter pipeline
- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'BrowserStacks'
    browserstackLocal: true
    bsLocalOptions: '{"verbose": true, "forceLocal": true}'
- script:
    npm install
    npm start &
  displayName: 'npm install start node based web application'
- script:
    gem install selenium-webdriver
    ruby testScript/automate_test.rb
  displayName: 'install ruby depedency and run test script'

- task: BrowserStackStopLocal@0
- task: BrowserStackResults@0