# An Azure Pipeline YAML file to deploy an iOS IPA Xcode and test it with Browserstack

# Trigger
trigger:
  branches:
    include:
    - master

# Variables
variables:
  browserstack_username: $(browserstack_username)
  browserstack_accesskey: $(browserstack_accesskey)

# Pool
pool:
  vmImage: 'macOS-latest'

# Steps
steps:
- task: Xcode@5
  displayName: 'Build iOS IPA'
  inputs:
    xcWorkspacePath: '$(workspacePath)'
    scheme: '$(scheme)'
    exportMethod: 'ad-hoc'
    signingOption: 'manual'
    signingIdentity: '$(signingIdentity)'
    provisioningProfileUuid: '$(provisioningProfileUuid)'
    packageApp: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish iOS IPA'
  inputs:
    PathtoPublish: '$(build.artifactStagingDirectory)'
    Artifact
